version: '3.1'

services:

  schemaservice:
    build: .
    image: oapass/schema-service:latest
    container_name: schemaservice
    env_file: .env
    ports:
      - "${SCHEMA_SERVICE_PORT}:${SCHEMA_SERVICE_PORT}"

  fcrepo:
    image: oapass/fcrepo:0.1.0@sha256:d667883f2ea3c9d4235a019be4c16f8796949d864e56490c57aa896bd672027f
    container_name: fcrepo
    env_file: .env
    ports:
      - "${FCREPO_PORT}:${FCREPO_PORT}"
